#
#                 _ __           _                _          _
#                | /_ |         | |              (_)        (_)
#  __ _ _   _  __| || |_ __   __| | ___ _ __ ___  _ _ __ ___ _
# / _` | | | |/ _` || | '_ \ / _` |/ _ \ '_ ` _ \| | '__/ __| |
#| (_| | |_| | (_| || | | | | (_| |  __/ | | | | | | | | (__| |
# \__,_|\__, |\__,_||_|_| |_|\__,_|\___|_| |_| |_|_|_|  \___|_|
#        __/ |
#       |___/
#

Format:
  global:
    Format: "§8[§l§c!§r§8]"
  default:
    Format: "§8[§l§a#§r§8]"

# LANGUAGE
#currently supported languages; tr (Turkish, Türkçe), en (English)
language: en